name: Mirror GitHub To CodeCommit

on: [push]

jobs:
  mirror_to_codecommit:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to CodeCommit
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/mirror-sre-challenge
          ssh_private_key: ${{ secrets.CODECOM_PRIV_KEY }}
          ssh_username: ${{ secrets.CODECOM_PRIV_KEY_ID }}